version: '3.9'
services:
  mongo:
    image: mongo:5.0.4-focal
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db

  app:
    build: .
    container_name: backend
    ports:
      - 3000:3000
    env_file:
      - .env.development.local
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017

volumes:
  mongodb:
