version: '3.9'
services:
  app:
    build: .
    container_name: backend
    ports:
      - 3000:3000
    env_file:
      - .env.development.local
    volumes:
      - .:/app
      - /app/node_modules
